import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Signup",
  description: "Generated by create next app",
};

const Signin = () => {
  return <h1>Signin</h1>;
};

export default Signin;
