import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const Login = () => {
  return <h1>Login</h1>;
};

export default Login;
