import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Dashboard = () => {
  return <h1>Dashboard</h1>;
};

export default Dashboard;
