import Donation from "@/components/ui/Donation";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Donations",
  description: "Generated by create next app",
};

const Donations = async () => {
  const res = await fetch(`http://localhost:5000/api/v1/posts`, {
    cache: "no-store",
  });
  const data = await res.json();
  console.log(data.data);

  return (
    <>
      <h1>tottal donations : {data.data.length}</h1>
      <Donation donations={data.data} />
    </>
  );
};

export default Donations;
