import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Statistics",
  description: "Generated by create next app",
};

const Statistics = () => {
  return <h1>Statistics</h1>;
};

export default Statistics;
