import React from "react";
import { Metadata } from "next";
import StatisticalRepresentation from "@/components/ui/StatisticalRepresentation";
export const metadata: Metadata = {
  title: "Statistics",
  description: "Generated by create next app",
};

const Statistics = () => {
  return (
    <div className="my-12 container mx-auto">
      <h1>Statistics</h1>
      <StatisticalRepresentation />
    </div>
  );
};

export default Statistics;
